### PR TITLE
Fix REPL exit instructions on Windows

### LINKED ISSUE #1677: REPL exit instructions don't work on Windows
It says to press `^D` to exit but that don't do nothing on `cmd.exe` on Win10: 
```
C:\rakudo>perl6

To exit type 'exit' or '^D'
> ^D^D^D^D^D^D^D^D^D^D
===SORRY!=== Error while compiling:
Bogus statement
------> <BOL><HERE>
    expecting any of:
        prefix
        term
> ^D
===SORRY!=== Error while compiling:
Bogus statement
------> <BOL><HERE>
    expecting any of:
        prefix
        term
> ^CTerminate batch job (Y/N)? y

C:\rakudo>perl6 -v
This is Rakudo version 2018.03-107-ge31dd96 built on MoarVM version 2018.03-31-gfdb5e4d
implementing Perl 6.c.
```

(partly related https://github.com/rakudo/rakudo/pull/1674 )

### PR DESCRIPTION
**Pull request by hankache**
Fixes #1677 and #1969

### CODE REVIEW

File: src/core.c/REPL.pm6 [hunk 1]
```diff
@@ -304,7 +304,11 @@ do {
 
         method repl-loop(*%adverbs) {
 
-            say "To exit type 'exit' or '^D'";
+            if $*DISTRO.is-win {
+                say "To exit type 'exit' or '^C'";
```
Comment (vrurg) [inline src/core.c/REPL.pm6]: Unix `^D` (EOF) is `^Z` on DOS-derivatives, isn't it?

File: t/02-rakudo/repl.t [hunk 2]
```diff
@@ -6,13 +6,23 @@ use Test::Helpers;
...
 my $*REPL-SCRUBBER = -> $_ is copy {
+    if $*DISTRO.is-win {
+    s/^^ "You may want to `zef install Readline` or `zef install Linenoise`"
+        " or use rlwrap for a line editor\n\n"//;
+    s/^^ "To exit type 'exit' or '^C'\n"//;
+    s:g/ ^^ "> "  //; # Strip out the prompts
+    s:g/    ">" $ //; # Strip out the final prompt
+    s:g/ ^^ "* "+ //; # Strip out the continuation-prompts
+    $_
+    } else {
```
Comment (vrurg) [inline t/02-rakudo/repl.t]: Same `^D` -> `^Z` note. But more important: the whole block is duplicate for the only purpose of changing one symbol in a message.

File: src/core.c/REPL.pm6 (hunk 1 above)
Comment (hankache) [reply src/core.c/REPL.pm6]: Indeed, but from a practical point of view, `^Z` requires the ENTER key to be hit afterwards on Windows, while `^C` will exit the REPL directly.
What do you propose I should move forward with? `^Z` or `^C`

Comment (vrurg) [reply src/core.c/REPL.pm6]: Hm... Luckily I'm not a Win user. All those inconsistencies are so confusing.

`^Z` would still be preferable because it's a request for graceful shutdown. Perhaps the message must reflect that nuance and contain `^Z Enter`?

Comment (hankache) [reply src/core.c/REPL.pm6]: Done updated to ^Z

File: t/02-rakudo/repl.t (hunk 2 above)
Comment (hankache) [reply t/02-rakudo/repl.t]: Updated to `^Z`.
I tried using `if else` and `?? !!` within the block in order not to duplicate but tests kept failing.

Comment (vrurg) [reply t/02-rakudo/repl.t]: Try wrapping just that s/// line which contains the message. Or better use [`$(code)` construct](https://docs.perl6.org/language/regexes#Regex_interpolation)

Comment (hankache) [reply t/02-rakudo/repl.t]: I just made the change. Is it ok now?

**Comment by hankache** [comment]
@vrurg is it merge-able?

**Comment by vrurg** [comment]
@hankache I would like to get rid of redundant duplication of printing 'To exit ...' message. Otherwise no problem.

**Comment by hankache** [comment]
@vrurg updated.

**Comment by vrurg** [comment]
Thanks!
