### PR TITLE
Fix storing of typed Hashes from a list

### LINKED ISSUE #5165: Parameterised hashes implementation detail sometimes leaks out
## The Problem
Parameterised hashes are not stored as expected (under certain circumstances).

## Expected Behaviour
Behaviour consistent with normal hashes.

```raku
my %h1      = :foo, :bar; say %(%h1,);  # OUTPUT: «{bar => True, foo => True}␤»
my %h2{Any} = :foo, :bar; say %(%h2,);  # OUTPUT: «{Str|bar => bar => True, Str|foo => foo => True}␤»
```

In the case of `%h2`, keys are apparently produced via `.WHICH`, with hash values consisting of the source hash pairs.

## Steps to Reproduce
The above examples hopefully provide a minimally reproducible case. The issue originally arose when working with hashes created from sets, e.g.

```raku
say %(<foo bar>.Set.Hash, :baz);        # OUTPUT: «{Str|bar => bar => True, Str|foo => foo => True, baz => True}␤»
```

where `<foo bar>.Set.Hash.WHAT` is `(Hash[Any,Any])`.

[This](https://gist.github.com/Whateverable/83607b0e8760cf60f18b694cf9ef2529) bisection suggests that problem may have been introduced in commit ecfb956bcf92488106a85f9462731095db11dfed.

## Environment
* Operating system: macOS 13.1.
* Compiler version (`perl6 -v` or `raku -v`): Rakudo™ v2022.12 .
* Bisection suggests that the issue has been present since Rakudo 2016.07.01.

### PR DESCRIPTION
**Pull request by 2colours**
Prior to this commit, a Hash with typed keys ("hash object") couldn't be
properly stored in another Hash, typed or untyped, if it appeared in a
list. This is a regression from July 2016,
commit https://github.com/rakudo/rakudo/commit/ecfb956bcf92488106a85f9462731095db11dfed .
In the affected timespan, the behavior was the following:

my %h{Any} = foo => 'bar', 12 => 'baz';
my %copy = (%h, );

The copy got recreated as the internal, `$!storage` representation.
Because of the current default implementation of `.hash`, the problem
appeared also when calling the `.hash` method on a list that contained a
"hash object", or enforcing hash context upon them with %().

STORE_AT_KEY is the method that takes care of creating an entry for an
implementation of a Hash, transforming the key and the value in a way the
underlying `$!storage` BOOTHash can hold them. When different
implementations of Hash are stored into another Hash (previously done with
the STORE_MAP method), this needs to be taken into account.

This commit fixes the problem by replacing non-dispatching STORE_MAP calls
with a PUSH_FROM_MAP method that needs to be provided for those
implementations of a Hash that have their own mapping to `$!storage`,
that is, typically the core implementations that have their own
STORE_AT_KEY. This PUSH_FROM_MAP knows how STORE_AT_KEY needs to be
called with regards to all of the elements retrieved from the Hash object
it's invoked on, meaning that all STORE_AT_KEY calls will happen with the
right arguments, at the cost of only one dispatch to the right PUSH_FROM_MAP
candidate.

Fixes #5165

### CODE REVIEW

**Review by lizmat — APPROVED** [review]

File: src/core.c/Hash/Object.pm6 [hunk 1]
```diff
@@ -33,6 +33,19 @@ my role Hash::Object[::TValue, ::TKey] does Associative[TValue] {
         )
     }
 
+    method PUSH_FROM_ITER(Mu \iter, \target --> Nil) {
```
Comment (vrurg) [inline src/core.c/Hash/Object.pm6:36]: Guessing, this one has to be an implementation details too, same as on `Hash`.

**Comment by lizmat** [comment]
After mulling a bit about this while cycling, I wonder why not change the *one* call to !STORE_MAP at https://github.com/rakudo/rakudo/blob/main/src/core.c/Hash.pm6#L97 to `$x.PUSH_FROM_ITER($temp)` and do the iterator creation inside those methods.

And then probably rename it to `PUSH_FROM_MAP` ?

File: src/core.c/Hash/Object.pm6 (hunk 1 above)
Comment (2colours) [reply src/core.c/Hash/Object.pm6:36]: Makes sense. I was just taking STORE_AT_KEY as the basis and saw no trait on it.

**Comment by 2colours** [comment]
Sounds good. I can make a new PR with that, if nobody objects.

**Comment by lizmat** [comment]
Or just adapt this PR  :-)   either would be fine

**Comment by 2colours** [comment]
Please check out the updated PR. :) I noticed a failing Rakudo test on my local installation while all spectests were passing - it was a test about profiling some way, I will take a look at it again. Otherwise it would seem that this is working now.

**Comment by lizmat** [comment]
Thanks!
